### ISSUE TITLE
v0.1.0 seems to be a mismatch

### ISSUE THREAD

**Issue by akiomik** [penpenpng/rx-nostr#4]
I tried v0.1.0 with the code from `app/main.ts` but it didn't work.

The following objects should be exported in `dist/index.es.js` at v0.1.0 (3c48c0b).

```js
export {
  pe as Nostr,
  so as RxBackwardReq,
  co as RxForwardReq,
  ao as createRxNostr,
  io as filterKind,
  ro as latest,
  no as uniq,
  oo as verify
};
```

In practice it looks like this:

```node
export {
  Je as BackwardReq,
  Ke as ForwardReq,
  $r as MonoFilterAccumulater,
  Nt as Nostr,
  Pr as Relays,
  zr as Req,
  Vr as collect,
  Mr as filterKind,
  Dr as latest,
  Zt as normalizeFilter,
  Kt as normalizeFilters,
  Wr as pickEvent,
  jr as uniq,
  Fr as verify
};
```

(ref: https://www.npmjs.com/package/rx-nostr?activeTab=code)

Please fix v0.1.0 or release a new version.

**Comment by penpenpng** [comment]
Thank you for your report!

It seems that I had mistakenly published an old build. It has been re-released as 0.2.0 with some bug fixes.
